allowBuilds:
  core-js: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - '@babel/generator@8.0.0'
  - '@babel/helper-string-parser@8.0.0'
  - '@babel/helper-validator-identifier@8.0.0'
  - '@babel/parser@8.0.0'
  - '@babel/types@8.0.0'
  - ast-kit@3.0.0
  - rolldown-plugin-dts@0.26.0
  - tsdown@0.22.3
